config:
  # MD013: Line length
  MD013:
    line_length: 100
    heading_line_length: 120
    code_block_line_length: 120

  # MD033: Allow inline HTML
  MD033: false

  # MD041: First line in file should be a top level heading
  MD041: false

  # MD024: Multiple headings with the same content
  MD024:
    siblings_only: true